typos={
'dont' : 'do not',
'cant': 'can not',
'cnt' : 'can not',
'doesnt' : 'does not',
'isnt' : 'is not',
'didnt' : 'did not',
'couldnt' : 'could not',
'cud' : 'could', 
'wasnt' : 'was not',
'wont': 'will not',
'wouldnt':'would not',
'ive' : 'I have',  
'il' : 'I will', # 'ill'
'theres' : 'there is' ,
'awsome' : 'awesome',
'awsum' : 'awesome',
'awsm' : 'awesome' ,
'dis': 'this' ,
'diz' : 'this' ,
'plzz' : 'please',
'plz':'please',
'pls' :'please' ,
'im' : 'I am',
'i m' : 'I am',
'u' : 'you',
'r' : 'are',
'ur' : 'your', # 'your are'
'u r': 'you are',
'b' : 'be',
'nd' : 'and',
'n' : 'and',
'bt' : 'but',
'nt' : 'not',
'coz' : 'because',
'cuz' : 'because',
'jus' : 'just',
'jst' : 'just',
'luv' : 'love',
'gud' : 'good',
'wel' : 'well',
'gr8' : 'great',
'grt' : 'great',
'Gr' : 'great',
'pics' :'pictures',
'pic' :'picture',
'hav' : 'have',
'nic' : 'nice',
'nyc' :'nice',
'9ce':'nice',
'agn' : 'again',
'thx':'thanks',
'tks' :'thanks',
'thanx':'thanks',
'thkq' : 'thank you',
'wel' : 'well',
'xcellent':'excellent',
'vry' : 'very',
'fav' : 'favorite',
'favo' : 'favorite',
'soo' : 'so',
'sooo': 'so',
'soooo': 'so',
'soooo':'so',
'ap': 'app',
'b4' : 'before',
'ez' : 'easy',
'w8' : 'wait',
'msg': 'message',
'alot': 'a lot',
'lota' : 'lot of' ,
'kinda' : 'kind of' ,
'omg': 'oh my god',
'gota' : 'going to' ,
'yea' : 'yeah',
'gf' : 'girlfriend',
'bf' : 'boyfriend',
}
